### ISSUE TITLE
BibTeX keys do not match Zotero default format

### ISSUE THREAD

**Issue by huldash** [willsALMANJ/lyz#9]
Hi,

I am using Lyz with an existing BibTeX database generated by exporting my Zotero library to BibTeX. I changed the Lyz setting for the BibTeX keys to author _ title _ year to match the Zotero default format and avoid duplicates in my bibliography. The problem is that Lyz includes the first two words in the title part of the key while Zotero only includes one word. So Zotero would write the key in your example as "tichy_foundations_1988", not "tichy_thefoundations_1988". Is there a way to make Lyz print the keys exactly like Zotero does?

Thank you,
Hulda

**Comment by bewantbe** [comment]
It seems that there is a simpler solution.

Lyz plugin actually got a full (vanilla) BibTex item from Zotero BibTeX translator (id=9cb70025-a888-4a29-a210-93ec52da40d4) which should be the same as the (written) bibtex file https://github.com/willsALMANJ/lyz/blob/6330629181dfb923022eb9fd063585a7703b3674/addon/chrome/content/lyz/lyz.js#L786

Then the `author` `year` and `title` are parsed in https://github.com/willsALMANJ/lyz/blob/6330629181dfb923022eb9fd063585a7703b3674/addon/chrome/content/lyz/lyz.js#L902

Instead of trying to match the Zotero BibTeX translator, we can directly use the key in the original BibTex item.
https://github.com/willsALMANJ/lyz/blob/6330629181dfb923022eb9fd063585a7703b3674/addon/chrome/content/lyz/lyz.js#L908

See the pull request (https://github.com/willsALMANJ/lyz/pull/28) for details.

**Comment by willsALMANJ** [comment]
Closing in favor of #29. Unfortunate it took four years to realize that this feature already existed.
